# Generated by Django 3.0.5 on 2020-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0002_auto_20200414_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="keywords",
            field=models.TextField(max_length=256, null=True),
        ),
    ]
