# Generated by Django 3.2 on 2021-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0005_auto_20200415_0234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
