# Generated by Django 4.0 on 2023-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
