# Generated by Django 3.0.5 on 2020-04-27 08:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
