# Generated by Django 3.0.5 on 2020-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0003_project_organization_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
