# Generated by Django 4.0 on 2022-09-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_alter_project_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
