# Generated by Django 4.0 on 2022-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
