version: "3.8"

services:
  apiserver:
    build:
      context: .
      target: dev
    image: kvdomingo/kvdomingo-xyz-api:latest
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/backend

  frontend:
    build:
      context: ./app
      target: dev
    image: kvdomingo/kvdomingo-xyz-web:latest
    env_file: ./app/.env
    ports:
      - 3000
    volumes:
      - ./app:/web/app
