services:
  api:
    build: api/
    image: kvdomingo/portfolio-api:latest
    user: "1000:1000"
    env_file: api/.env
    volumes:
      - ./api:/backend

  ui:
    image: node:18-alpine
    user: "1000:1000"
    environment:
      - NODE_ENV=development
    working_dir: /web
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn dev --host 0.0.0.0 --port 3000"
    volumes:
      - ./ui:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kvdomingo-xyz.rule=Host(`kvdomingo.localhost`)"
      - "traefik.http.routers.kvdomingo-xyz.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.kvdomingo-xyz.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - default
      - gateway
      

  db:
    image: asia.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0
    volumes:
      - ./credentials.json:/config
    command:
      - my-projects-306716:asia-east1:schedule-bot
      - "--credentials-file=/config"
      - "--address=0.0.0.0"
      - "--port=3306"

networks:
  gateway:
    external: true
