version: "3.8"

networks:
  gateway:
    external: true

services:
  backend:
    build:
      context: .
      target: dev
    image: kvdomingo/kvdomingo-xyz-api:latest
    env_file: .env
    volumes:
      - .:/kvd

  frontend:
    build:
      context: ./webapp
      target: dev
    image: kvdomingo/kvdomingo-xyz-web:latest
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
      - WDS_SOCKET_PORT=0
    volumes:
      - ./webapp:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=${HTTP_PORT}
    volumes:
      - ./proxy/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/kvdomingo.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kvdomingo-xyz.rule=Host(`kvdomingo.localhost`)"
      - "traefik.http.routers.kvdomingo-xyz.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.kvdomingo-xyz.loadbalancer.server.port=${HTTP_PORT}"
    restart: unless-stopped
    networks:
      - default
      - gateway