version: "3.8"

networks:
  gateway:
    external: true

services:
  api:
    build: api/
    image: kvdomingo/portfolio-api:latest
    env_file: api/.env
    volumes:
      - ./api:/backend

  ui:
    image: node:16-alpine
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
      - WDS_SOCKET_PORT=0
    working_dir: /web
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn start"
    volumes:
      - ./app:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kvdomingo-xyz.rule=Host(`kvdomingo.localhost`)"
      - "traefik.http.routers.kvdomingo-xyz.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.kvdomingo-xyz.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - default
      - gateway
