version: '3'

env:
  NAME: kvdomingo-dev

dotenv:
  - api/.env

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name {{.NAME}} up --detach --build --remove-orphans

  setup:
    desc: Run initial setup
    dir: api/
    cmds:
      - poetry install
      - poetry run python -m scripts.make_env

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.NAME}} stop

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.NAME}} exec -- {{.CLI_ARGS}}

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose --project-name {{.NAME}} exec -- proxy nginx -s reload

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.NAME}} restart {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.NAME}} down --remove-orphans {{.CLI_ARGS}}
