version: '3'

env:
  NAME: kvdomingo-dev

dotenv:
  - .env

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose -p {{.NAME}} up -d --build
      - task logs

  setup:
    desc: Run initial setup
    dir: api/
    cmds:
      - poetry install
      - poetry run python -m scripts.make_env

  sqlproxy:
    desc: Start the gcloud SQL proxy
    cmds:
      - cloud_sql_proxy -instances=my-projects-306716:asia-east1:schedule-bot=tcp:0.0.0.0:3306

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose -p {{.NAME}} logs --follow {{.CLI_ARGS}}

  shutdown:
    desc: Stop containers
    cmds:
      - docker compose -p {{.NAME}} stop

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose -p {{.NAME}} exec -- {{.CLI_ARGS}}

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose -p {{.NAME}} exec -- proxy nginx -s reload

  restart:
    desc: Restart containers
    cmds:
      - docker compose -p {{.NAME}} restart {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose -p {{.NAME}} down -v --remove-orphans
