# Generated by Django 3.1 on 2020-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_auto_20200713_0201"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technologies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BE", "Backend"),
                            ("FE", "Frontend"),
                            ("DV", "Data & Vis"),
                            ("CI", "CI/CD & Platforms"),
                        ],
                        max_length=2,
                    ),
                ),
                ("alt", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name="reference",
            options={"ordering": ["id"]},
        ),
    ]
