# Generated by Django 3.1.2 on 2020-10-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_auto_20200930_0250"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
