# Generated by Django 3.1.2 on 2020-10-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_technology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={
                "ordering": ["category", "order"],
                "verbose_name_plural": "technologies",
            },
        ),
        migrations.AlterField(
            model_name="technology",
            name="category",
            field=models.CharField(
                choices=[
                    ("BE", "Backend"),
                    ("FE", "Frontend"),
                    ("DB", "Database Management"),
                    ("DV", "Data & Vis"),
                    ("CI", "CI/CD & Platforms"),
                ],
                max_length=2,
            ),
        ),
    ]
