# Generated by Django 3.0.5 on 2020-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
