# Generated by Django 3.0.5 on 2020-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0007_auto_20200412_0208"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=256)),
                ("number", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
            ],
        ),
    ]
