# Generated by Django 3.0.5 on 2020-04-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0008_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="prefix",
            new_name="name",
        ),
    ]
