# Generated by Django 3.0.5 on 2020-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0009_auto_20200412_0420"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="", max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
