# Generated by Django 3.2 on 2021-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0019_auto_20200514_1916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
