# Generated by Django 4.0 on 2023-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svip', '0023_alter_blogpost_body_alter_blogpost_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
