# Generated by Django 3.0.8 on 2020-07-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200713_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-date_granted']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AddField(
            model_name='work',
            name='related_project',
            field=models.SlugField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
