# Generated by Django 3.0.8 on 2020-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200713_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='related_project',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
