# Generated by Django 3.1 on 2020-09-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_auto_20200930_0248"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technologies",
            options={"ordering": ["category"]},
        ),
    ]
