# Generated by Django 3.1 on 2020-09-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200930_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category'], 'verbose_name_plural': 'technologies'},
        ),
    ]
