# Generated by Django 3.1.5 on 2021-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201014_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(max_length=32)),
                ('section_body', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('BE', 'Backend'), ('FE', 'Frontend'), ('DB', 'Database'), ('DV', 'Data & Vis'), ('CI', 'CI/CD & Platforms')], max_length=2),
        ),
    ]
