# Generated by Django 3.1.5 on 2021-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210127_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=256)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
