# Generated by Django 3.2 on 2021-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210729_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
