# Generated by Django 3.2.9 on 2021-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_certification_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('BE', 'Backend'), ('FE', 'Frontend'), ('DB', 'Database'), ('DV', 'Data & Vis'), ('CI', 'CI/CD & Cloud')], max_length=2),
        ),
    ]
