# Generated by Django 3.0.5 on 2020-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('shoot_date', models.DateTimeField(blank=True)),
                ('cover_image', models.URLField(max_length=256)),
                ('keywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
    ]
