# Generated by Django 3.0.5 on 2020-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svip', '0015_blogpost_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
