# Generated by Django 3.0.5 on 2020-04-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("svip", "0017_course_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="svip.Course",
                to_field="number",
            ),
        ),
    ]
