# Generated by Django 4.0 on 2022-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svip', '0021_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
