# Generated by Django 4.0 on 2022-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svip', '0022_alter_blogpost_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
